version: '3.9'

services:
  test_redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - app_data:/data
  test_app:
    build: .
    image: walosha/backend_test_api
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - test_db
      - test_redis

  test_db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ./.env

  test_mongo_admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.env

volumes:
  app_data: {}
